using Day14_DataStructures;
Console.WriteLine("Hello World!");
UC6_RemoveLastNode list = new UC6_RemoveLastNode();
list.Add(56);
list.Add(30);
list.Add(70);
//list.InsertAtParticularPosition(1,30);
//list.RemoveFirstNode();
list.RemovaLastNode();
list.Display();